# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-05 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': '个人信息', 'verbose_name_plural': '所有用户信息'},
        ),
        migrations.AlterField(
            model_name='person',
            name='birth',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(blank=True, db_column='nick', max_length=32, null=True),
        ),
        migrations.AlterModelTable(
            name='person',
            table='Person',
        ),
    ]
