# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-06 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20200406_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='repertory',
            field=models.IntegerField(default=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='sale',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
