# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-02 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_auto_20200401_1815'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('books', models.ManyToManyField(to='app01.Book')),
            ],
        ),
    ]
