# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-11 06:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(choices=[('1', '黄土高坡总公司'), ('2', '家里蹲分公司'), ('3', '德玛西亚分公司')], max_length=32, verbose_name='公司'),
        ),
        migrations.AlterField(
            model_name='user',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='上次登陆时间'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=32, verbose_name='密码'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=32, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(max_length=32, verbose_name='职位'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=32, unique=True, verbose_name='用户名'),
        ),
    ]
