# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-12 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='文章标题')),
                ('abstract', models.CharField(max_length=256, verbose_name='文章摘要')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('creat_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('delete_status', models.BooleanField(default=False, verbose_name='删除状态')),
                ('author', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app01.User', verbose_name='作者')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='板块标题')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='评论内容')),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=True, verbose_name='审核状态')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app01.Article', verbose_name='文章')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app01.User', verbose_name='评论者')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='app01.Category', verbose_name='分类'),
        ),
    ]
