# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-12 12:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20200412_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='文章内容')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='detail',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='app01.ArticleDetail'),
            preserve_default=False,
        ),
    ]
