# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-04-15 09:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0005_auto_20200412_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='delete_status',
        ),
        migrations.AddField(
            model_name='article',
            name='publish_status',
            field=models.BooleanField(choices=[(False, '未发布'), (True, '发布')], default=False, verbose_name='发布状态'),
        ),
    ]
